# SPDX-FileCopyrightText: 2023 Arjen Hiemstra <ahiemstra@heimr.nl>
# SPDX-License-Identifier: BSD-2-Clause

id:              org.kde.krdp
branch:          master
runtime:         org.kde.Platform
runtime-version: "6.7"
sdk:             org.kde.Sdk

command: krdpserver
tags:
-   nightly
desktop-file-name-suffix: " (Nightly)"

finish-args:
-   "--share=ipc"
-   "--share=network"
-   "--device=all"
-   "--socket=x11"
-   "--socket=wayland"
-   "--filesystem=home:ro"
-   "--env=QT_LOGGING_DEBUG=*.debug=true qt.qpa.input*.debug=false"

add-extensions: {}

modules:
-   name: FreeRDP
    config-opts:
    -   "-DWITH_SERVER=ON"
    -   "-DCHANNEL_URBDRC=OFF"
    -   "-DWITH_FFMPEG=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://github.com/FreeRDP/FreeRDP
        tag: 2.10.0

-   name: libsecret
    buildsystem: meson
    sources:
    -   type: archive
        url: "https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.5.tar.xz"
        sha256: "3fb3ce340fcd7db54d87c893e69bfc2b1f6e4d4b279065ffe66dac9f0fd12b4d"
    config-opts:
    -   "-Dgcrypt=false"
    -   "-Dgtk_doc=false"
    -   "-Dintrospection=false"
    -   "-Dmanpage=false"
    -   "-Dvapi=false"

-   name: qtkeychain
    buildsystem: cmake-ninja
    sources:
    -   type: archive
        url: "https://github.com/frankosterfeld/qtkeychain/archive/0.14.2.tar.gz"
        sha256: "cf2e972b783ba66334a79a30f6b3a1ea794a1dc574d6c3bebae5ffd2f0399571"
    config-opts:
    -   "-DCMAKE_INSTALL_LIBDIR=/app/lib"
    -   "-DLIB_INSTALL_DIR=/app/lib"
    -   "-DBUILD_TRANSLATIONS=NO"
    -   "-DBUILD_WITH_QT6=ON"

-   name: kpipewire
    config-opts:
    -   "-DBUILD_TESTING=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://invent.kde.org/plasma/kpipewire

-   name: krdp
    buildsystem: cmake-ninja
    config-opts:
    -   "-DBUILD_PLASMA_SESSION=OFF"
    sources:
    -   type: dir
        path: "."
