# SPDX-FileCopyrightText: 2023 Arjen Hiemstra <ahiemstra@heimr.nl>
# SPDX-License-Identifier: BSD-2-Clause

id:              org.kde.krdp
branch:          master
runtime:         org.kde.Platform
runtime-version: "6.6"
sdk:             org.kde.Sdk

command: krdpserver
tags:
-   nightly
desktop-file-name-suffix: " (Nightly)"

finish-args:
-   "--share=ipc"
-   "--share=network"
-   "--device=all"
-   "--socket=x11"
-   "--socket=wayland"
-   "--filesystem=home:ro"
-   "--env=QT_LOGGING_DEBUG=*.debug=true qt.qpa.input*.debug=false"

add-extensions: {}

modules:
-   name: FreeRDP
    config-opts:
    -   "-DWITH_SERVER=ON"
    -   "-DCHANNEL_URBDRC=OFF"
    -   "-DWITH_FFMPEG=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://github.com/FreeRDP/FreeRDP
        tag: 2.10.0

-   name: extra-cmake-modules
    config-opts:
    -   "-DENABLE_TESTING=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://invent.kde.org/frameworks/extra-cmake-modules.git

-   name: kpipewire
    config-opts:
    -   "-DBUILD_TESTING=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://invent.kde.org/plasma/kpipewire

# Temporary addition until SDK is updated
-   name: kconfig
    config-opts:
    -   "-DBUILD_TESTING=OFF"
    buildsystem: cmake-ninja
    sources:
    -   type: git
        url: https://invent.kde.org/frameworks/kconfig

-   name: krdp
    buildsystem: cmake-ninja
    config-opts:
    -   "-DBUILD_PLASMA_SESSION=OFF"
    sources:
    -   type: dir
        path: "."
