# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['@all']
    'require':
      'frameworks/extra-cmake-modules': '@latest-kf6'
      'frameworks/kconfig': '@latest-kf6'
      'frameworks/kdbusaddons': '@latest-kf6'
      'frameworks/kstatusnotifieritem': '@latest-kf6'
      'frameworks/kcmutils': '@latest-kf6'
      'frameworks/kcrash': '@latest-kf6'
      'plasma/kpipewire': '@latest-kf6'
      'third-party/qtkeychain': '@latest'

Options:
  require-passing-tests-on: ['@all']
  enable-lsan: True
