# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

[Desktop Entry]
Type=Application
Exec=@CMAKE_INSTALL_PREFIX@/bin/krdpserver
Icon=krfb
Terminal=false
NoDisplay=true
Name=KRdp
Name[ar]=كي أردبي
Name[ast]=KRdp
Name[bg]=KRdp
Name[ca]=KRdp
Name[ca@valencia]=KRdp
Name[cs]=KRdp
Name[de]=KRdp
Name[en_GB]=KRdp
Name[eo]=KRdp
Name[es]=KRdp
Name[eu]=KRdp
Name[fi]=KRdp
Name[fr]=KRdp
Name[gl]=KRdp
Name[he]=KRdp
Name[hu]=KRdp
Name[ia]=KRdp
Name[is]=KRdp
Name[it]=KRdp
Name[ka]=KRdp
Name[ko]=KRdp
Name[lt]=KRdp
Name[lv]=KRdp
Name[nl]=KRdp
Name[nn]=KRdp
Name[pa]=KRdp
Name[pl]=KRdp
Name[pt_BR]=KRdp
Name[ro]=KRdp
Name[ru]=KRdp
Name[sa]=KRdp
Name[sk]=KRdp
Name[sl]=KRdp
Name[sv]=KRDP
Name[tr]=KRdp
Name[uk]=KRdp
Name[x-test]=xxKRdpxx
Name[zh_CN]=KRDP
Name[zh_TW]=KRdp
GenericName=Desktop Sharing (RDP)
GenericName[ar]=مشاركة سطح المكتب (أردبي)
GenericName[ast]=Compartición del escritoriu (RDP)
GenericName[bg]=Споделяне на работния плот
GenericName[ca]=Compartició de l'escriptori (RDP)
GenericName[ca@valencia]=Compartiu l'escriptori (RDP)
GenericName[cs]=Sdílení pracovní plochy (RDP)
GenericName[de]=Freigabe der Arbeitsfläche (RDP)
GenericName[en_GB]=Desktop Sharing (RDP)
GenericName[eo]=Kundivido de Labortablo (RDP)
GenericName[es]=Compartir el escritorio (RDP)
GenericName[eu]=Mahaigaina partekatzea (RDP)
GenericName[fi]=Työpöydän jako (RDP)
GenericName[fr]=Partage de bureaux (RDP)
GenericName[gl]=Compartición do escritorio (RDP)
GenericName[he]=שיתוף שולחנות עבודה (RDP)
GenericName[hu]=Asztalmegosztás (RDP)
GenericName[ia]=Compartir de scriptorio (RDP)
GenericName[is]=Skjáborðsmiðlun (RDP)
GenericName[it]=Condivisione del desktop (RDP)
GenericName[ka]=სამუშაო მაგიდის გაზიარება (RDP)
GenericName[ko]=데스크톱 공유(RDP)
GenericName[lt]=Darbalaukio bendrinimas (RDP)
GenericName[lv]=Darbvirsmas kopīgošana (RDP)
GenericName[nl]=Bureaublad delen (RDP)
GenericName[nn]=Skrivebordsdeling (RDP)
GenericName[pa]=ਡੈਸਕਟਾਪ ਸ਼ੇਅਰਿੰਗ (RDP)
GenericName[pl]=Współdzielenie pulpitu (RDP)
GenericName[pt_BR]=Compartilhamento da área de trabalho (RDP)
GenericName[ro]=Partajare birou (RDP)
GenericName[ru]=Совместный доступ к рабочему столу (RDP)
GenericName[sa]=कार्यमुखम् साझाकरणम् (RDP)
GenericName[sk]=Zdieľanie plochy (RDP)
GenericName[sl]=Deljenje namizja (RDP)
GenericName[sv]=Skrivbordsdelning (RDP)
GenericName[ta]=பணிமேடைப் பகிர்வு (RDP)
GenericName[tr]=Masaüstü Paylaşımı (RDP)
GenericName[uk]=Спільне користування стільницею (RDP)
GenericName[x-test]=xxDesktop Sharing (RDP)xx
GenericName[zh_CN]=桌面共享 (RDP)
GenericName[zh_TW]=桌面分享 (RDP)
Comment=Desktop Sharing
Comment[ar]=مشاركة سطح المكتب
Comment[ast]=Compartición del escritoriu
Comment[bg]=Споделяне на работния плот
Comment[ca]=Compartició de l'escriptori
Comment[ca@valencia]=Compartiu l'escriptori
Comment[cs]=Sdílení pracovní plochy
Comment[de]=Arbeitsflächen-Freigabe
Comment[en_GB]=Desktop Sharing
Comment[eo]=Kundivido de Labortablo
Comment[es]=Compartir el escritorio
Comment[eu]=Mahaigaina partekatzea
Comment[fi]=Työpöydän jako
Comment[fr]=Partage de bureaux
Comment[gl]=Compartición do escritorio.
Comment[he]=שיתוף שולחנות עבודה
Comment[hu]=Asztalmegosztás
Comment[ia]=Compartir de scriptorio
Comment[is]=Skjáborðamiðlun
Comment[it]=Condivisione del desktop
Comment[ka]=სამუშაო მაგიდის გაზიარება
Comment[ko]=데스크톱 공유
Comment[lt]=Darbalaukio bendrinimas
Comment[lv]=Darbvirsmas kopīgošana
Comment[nl]=Bureaublad delen
Comment[nn]=Skrivebordsdeling
Comment[pa]=ਡੈਸਕਟਾਪ ਸ਼ੇਅਰਿੰਗ
Comment[pl]=Współdzielenie pulpitu
Comment[pt_BR]=Compartilhamento da área de trabalho
Comment[ro]=Partajare birou
Comment[ru]=Совместный доступ к рабочему столу
Comment[sa]=कार्यमुखम् साझाकरणम्
Comment[sk]=Zdieľanie pracovnej plochy
Comment[sl]=Deljenje namizja
Comment[sv]=Skrivbordsdelning
Comment[ta]=பணிமேடைப் பகிர்வு
Comment[tr]=Masaüstü Paylaşımı
Comment[uk]=Спільні стільниці
Comment[x-test]=xxDesktop Sharingxx
Comment[zh_CN]=桌面共享
Comment[zh_TW]=桌面分享
Categories=Qt;KDE;Network;RemoteAccess;
X-KDE-Wayland-Interfaces=org_kde_kwin_fake_input,zkde_screencast_unstable_v1
